image: gitpod/workspace-full
tasks:
  - init: bundle # Just install our Ruby deps
    command: bundle exec jekyll serve --incremental -V -l -P 4000 --baseurl https://git-gram.gq # Then serve.
ports:
  - port: 4000
    onOpen: notify